name: ultimate_containers
description: CSS-Like stylesheets for Flutter.
version: 1.0.0-dev8
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
